### ISSUE TITLE
CLI does not accept config file in json format

### ISSUE THREAD

**Issue by casio** [suitcss/preprocessor#65]
`$ suitcss -c .suitconfig index.css` raises like below when using a config file like

```
{
  "root": "src"
}
```

```
.suitconfig:2
  "root": "src"
        ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.../node_modules/suitcss-preprocessor/bin/suitcss:68:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

**Comment by simonsmith** [comment]
Interesting. I don't think we've tried with `rc` style config files. If you rename to `suitconfig.json` does it work?

**Comment by casio** [comment]
nope : )

**Comment by simonsmith** [comment]
Okay thanks 👍

**Comment by giuseppeg** [comment]
The `json` extension is mandatory because we `require` that file instead of reading from the disk and `JSON.parse` it.

**Comment by giuseppeg** [comment]
btw it works for me

**Comment by casio** [comment]
@giuseppeg oops, you're right! 
the `"root"` option however is still ignored, so I confused that with this actual issue, sry!

that being said, does it maybe make sense to change the current implementation(using `require`) to  `JSON.parse`? 
probably just me, but I didnt really think the extension would be relevant & I was assuming I could name the file arbitrarily. maybe a hint in the docs would also help?

**Comment by simonsmith** [comment]
@casio The docs do specify JavaScript or JSON but I agree we should be flexible and try to parse whatever the user sends across.

We can leave this issue open to make that change.
